[mcp_servers.comet-mcp]
command = "npx"
args = ["-y", "comet-mcp"]


[mcp_servers.notion]
url = "https://mcp.notion.com/mcp"

[mcp_servers.chrome-devtools]
command = "npx"
args = ["chrome-devtools-mcp@latest",
        "--userDataDir=/Users/nasiwakmac/.cache/chrome-devtools-mcp/chrome-profile"]
